project:
  type: website
  output-dir: docs

website:
  title: "Gabriel Palucci Rosa"
  navbar:
    logo: "solo.png"
    background: primary
    right:
      - text: About
        menu:
          - text: English
            href: about_en.qmd
          - text: Português
            href: about_pt.qmd
          - text: Talk
            href: conversa.qmd
      - icon: github
        href: https://github.com/

format:
  html:
    theme:
    - cosmo
    - theme.scss

editor: visual
comments:
  giscus:
    repo: GabrielPalucci/Blog
    

