project:
  type: website
  output-dir: docs

website:

  title: "Gabriel Palucci Rosa"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
        
        
        
format:
  html:
    theme: 
      light: theme.scss

editor: visual
comments:
  giscus:
    repo: GabrielPalucci/Blog
    

