project:
  type: website
  output-dir: docs

website:
  title: "Gabriel Palucci Rosa"
    right:
      - icon: github
        href: https://github.com/GabrielPalucci/
      - icon: envelope
        href: gabrielpalucciufu@gmail.com
  navbar:
    logo: "solo.png"
    background: primary
    right:
      - text: About
        menu:
          - text: English
            href: about/about_en.qmd
          - text: Português
            href: about/about_pt.qmd
      - text: Talk
        menu:
          - text: English
            href: talk/talk_en.qmd
          - text: Português
            href: talk/talk_pt.qmd
      - text: Research
        href: research.qmd
      - icon: github
        href: https://github.com/
    page-footer:
     left: "Website made with [Quarto](https://quarto.org/), by Gabriel Palucci Rosa."

format:
  html:
    theme:
    - cosmo
    - theme.scss

editor: visual
comments:
  giscus:
    repo: GabrielPalucci/Blog
    

