project:
  type: website
  output-dir: docs
  
website:
  title: "Gabriel Palucci Rosa"
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/), by Gabriel Palucci Rosa."
    right:
      - icon: github
        href: https://github.com/GabrielPalucci/
      - icon: envelope
        href: gabrielpalucciufu@gmail.com
  navbar:
    logo: "planta.png"
    right:
      - text: ABOUT
        menu:
          - text: English
            href: about/about_e.qmd
          - text: Português
            href: about/about_p.qmd
      - text: PUBLICATIONS
        href: publication.qmd
      - text: BLOG
        href: blog.qmd
      - icon: github
        href: https://github.com/
        
format:
  html:
    theme:
    - cosmo
    - theme.scss
linestretch: 2


editor: visual
comments:
  giscus:
    repo: GabrielPalucci/Blogs
    

